# perf script event handlers, generated by perf script -g python
# Licensed under the terms of the GNU GPL License version 2

# The common_* event handler fields are the most useful fields common to
# all events.  They don't necessarily correspond to the 'common_*' fields
# in the format files.  Those fields not available as handler params can
# be retrieved using Python functions of the form common_*(context).
# See the perf-script-python Documentation for the list of available functions.

from __future__ import print_function

import os
import sys

sys.path.append(os.environ['PERF_EXEC_PATH'] + \
    '/scripts/python/Perf-Trace-Util/lib/Perf/Trace')

from perf_trace_context import *
from Core import *
from text_histogram3 import histogram  # noqa: E402

last_vhnotify = None
last_vhnotify_to_dpdk = None
notify_notified_delta = []
notify_dpdk_delta = []

def trace_begin():
    print("in trace_begin")

def trace_end():
    histogram(notify_notified_delta)
    histogram(notify_dpdk_delta)

def probe_ovs__vhnotify(event_name, context, common_cpu,
    common_secs, common_nsecs, common_pid, common_comm,
    common_callchain, __probe_ip, perf_sample_dict):

    global last_vhnotify
    global last_vhnotify_to_dpdk

    last_vhnotify = common_nsecs
    last_vhnotify_to_dpdk = common_nsecs

def probe_ovs__vhnotified(event_name, context, common_cpu,
    common_secs, common_nsecs, common_pid, common_comm,
    common_callchain, __probe_ip, perf_sample_dict):

    global last_vhnotify
    global notify_notified_delta

    if last_vhnotify is not None:
        notify_notified_delta.append(common_nsecs - last_vhnotify)
        last_vhnotify = None

def probe_ovs__dpdknotified__return(event_name, context, common_cpu,
    common_secs, common_nsecs, common_pid, common_comm,
    common_callchain, __probe_ip, perf_sample_dict):

    global last_vhnotify_to_dpdk
    global notify_dpdk_delta

    if last_vhnotify_to_dpdk is not None:
        notify_dpdk_delta.append(common_nsecs - last_vhnotify_to_dpdk)
        last_vhnotify_to_dpdk = None
